// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCef_rufslv_CPXCVVjVx0p7CPso5SRiVM',
    appId: '1:190836363748:web:cc684ba52cb1f1dece37f1',
    messagingSenderId: '190836363748',
    projectId: 'chat-up-9d23a',
    authDomain: 'chat-up-9d23a.firebaseapp.com',
    storageBucket: 'chat-up-9d23a.appspot.com',
    measurementId: 'G-B6705KD31H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB09HOoPrFr1yPRlqPhDR_MKAyJSXfTqUg',
    appId: '1:190836363748:android:9158214de22763efce37f1',
    messagingSenderId: '190836363748',
    projectId: 'chat-up-9d23a',
    storageBucket: 'chat-up-9d23a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEJY3JruoN54l0uJ-diPiwMy6pCF_Pwus',
    appId: '1:190836363748:ios:29c7d0c4fe6587ffce37f1',
    messagingSenderId: '190836363748',
    projectId: 'chat-up-9d23a',
    storageBucket: 'chat-up-9d23a.appspot.com',
    iosBundleId: 'com.example.snapchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEJY3JruoN54l0uJ-diPiwMy6pCF_Pwus',
    appId: '1:190836363748:ios:2a0cad309198f639ce37f1',
    messagingSenderId: '190836363748',
    projectId: 'chat-up-9d23a',
    storageBucket: 'chat-up-9d23a.appspot.com',
    iosBundleId: 'com.example.snapchat.RunnerTests',
  );
}
